<?php
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 19.11.2018
 * Time: 10:02
 */

namespace bookkeeping\entities\widgets;


use bookkeeping\entities\Category;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class CategoryWidget extends Widget
{
    /**
     * @var Category $rootCategory
     */
    public $rootCategory;
    public $spaces = 0;
    private $interval = 1;
    private $tab = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $spaces = $this->spaces;
        while ($spaces-- > 0) {
            $this->tab .= '<p>';
        }
    }

    public function run()
    {
        $output = '<ul>';

        if ($this->spaces > 0) {
            $output .= '<li>';
        }

        $output .= $this->tab.$this->rootCategory->name.'<br>';

        $output .= $this->tab.Html::a(
                'Добавить категорию',
                Url::to(['category/create']),
                [
                    'data-method' => 'POST',
                    'data-params' => [
                        'familyId' => $this->rootCategory->familyId,
                        'parentId' => $this->rootCategory->id,
                    ],
                ]
            );

        foreach ($this->rootCategory->getChildren()->all() as $category) {
            $output .= CategoryWidget::widget([
                    'rootCategory' => $category,
                    'spaces' => $this->spaces + $this->interval,
                ]).'<br>';
        }

        return $output.'</ul>';
    }
}