<?php
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 05.01.2019
 * Time: 13:09
 */

namespace bookkeeping\entities\widgets;

use bookkeeping\constants\SelfPostActions;
use bookkeeping\entities\Transaction;
use yii\base\Widget;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\Html;
use yii\helpers\Url;

class TransactionWidget extends Widget
{
    /**
     * @var Transaction $transaction
     */
    public $transaction;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $header = $this->transaction;

        $transactionDropdownItems = [];

        $transactionDropdownItems[] = [
            'label' => 'Удалить',
            'url' => Url::current(),
            'linkOptions' => [
                'data' => [
                    'method' => 'POST',
                    'params' => [
                        'type' => 'self_post',
                        'operation' => SelfPostActions::$transaction_remove,
                        'id' => $this->transaction->id,
                    ],
                ]
            ]
        ];

        $transactionActions = ButtonDropdown::widget([
            'encodeLabel' => false,
            'label' => '',
            'dropdown' =>[
                'encodeLabels' => false,
                'items' => $transactionDropdownItems
            ]
        ]);

        return $header . $transactionActions;
    }
}