<?php
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 23.01.2019
 * Time: 14:00
 */

namespace bookkeeping\entities\widgets;

use yii\base\Widget;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\Url;

class TransactionListWidget extends Widget
{
    /**
     * @var int $rootCategoryId
     */
    public $rootCategoryId;

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $transactionView = TransactionsWidget::widget([
            'categoryId' => $this->rootCategoryId
        ]) . '<br>';

        $transactionDropdownItems = [];

        $transactionDropdownItems[] = [
            'label' => 'Добавить',
            'url' => Url::to(['transaction/create']),
            'linkOptions' => [
                'data' => [
                    'method' => 'POST',
                    'params' => [
                        'id' => $this->rootCategoryId,
                    ],
                ]
            ]
        ];

        $transactionActions = ButtonDropdown::widget([
            'encodeLabel' => false,
            'label' => '',
            'dropdown' =>[
                'encodeLabels' => false,
                'items' => $transactionDropdownItems
            ]
        ]);

        $output = '';

        //Транзакции
        $transactionHeader = 'Операции: ' . $transactionActions . '<br>';
        $output .= $transactionHeader
            . $transactionView;

        return $output;
    }
}