<?php
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 03.01.2019
 * Time: 12:20
 */

namespace bookkeeping\entities\widgets;

use bookkeeping\repositories\bookkeeping\TransactionRepository;
use yii\base\Widget;
use yii\helpers\Html;

class TransactionsWidget extends Widget
{
    /**
     * @var integer $categoryId
     */
    public $categoryId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        /**
         * @var TransactionRepository $repo
         */
        $repo = new TransactionRepository();

        try {
            $transactions = $repo->getByCategoryId($this->categoryId);

            $view = Html::ul($transactions, ['item' => function ($item, $index) {
                return TransactionWidget::widget([
                    'transaction' => $item
                ]) . '<br>';
            }]);
        } catch (\DomainException $e) {
            $view = '';
        }

        return $view;
    }
}